apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram-1
        type: telegram
        settings:
          bottoken: $__env{TG_BOT_TOKEN}
          chatid: "$__env{TG_CHAT_ID}"
        disableResolveMessage: false
